.github/workflows/main.yml, bootstrap.py, ci/setup-askpass.sh, poet.toml, src/commands/build.stanza, src/dependency.stanza
- Change `poet.toml` specifier format to not specify the full URL with a protocol (e.g. `git` or `https:`) and instead let `poet` form the proper protocol to use automatically.
- Use `https` to sync/fetch dependencies when `GIT_ASKPASS` is set. (Necessary so CI can clone dependencies properly)
- Enforce that every locator contains a version (e.g. `foo/bar|latest`)
=> Release v0.1.0

src/commands/build.stanza, src/utils.stanza
- Print debug output to standard error.
- Add some more tracing to `poet build`
- Flush `info` stream after writing (to fix weird output bug in CI)
=> Logging improvements

src/utils.stanza
Use program name instead of program path when logging output, e.g:
(before)
```
$ ./poet build
./poet: build: cloning dep|0.1.0
```
(after)
```
$ ./poet build
poet: build: cloning dep|0.1.0
```
Internal:
- Fix `base-name?` to return a string instead of the representation of a
`PathElement` (e.g. `NamedPath("foo")`)
- Make `last?` operate on a `Seqable` instead of an `IndexedCollection`
(more general)
=> logging: use program name instead of program path in output

.github/workflows/main.yml, bootstrap.py, src/commands/build.stanza, src/dependency.stanza, src/utils.stanza
Control the protocol `poet` uses explicitly using the `POET_PROTOCOL` environment variable, rather than using this weird specific support for `GIT_ASKPASS`.
Supports two values:
- `git`: which forms a URL for the locator using the scheme `git@github.com:<locator>`
- `https`: which forms a URL for the locator using the scheme `https://github.com:<locator>`
When unset, the default is to use `git`.
Also: switch the CI over to using `POET_PROTOCOL=https`, and add support in `./bootstrap.py`.
=> Add `POET_PROTOCOL` env variable, remove `GIT_ASKPASS` support

src/utils.stanza
Was due to the lack of a catch-all clause in the `switch`.
=> build: don't fatal when `POET_PROTOCOL` is set to an invalid value

.github/workflows/main.yml
Due to the repository settings not allowing pushes to master without a PR, it's not possible to merge to master without the changes being clean in the first place.
This avoids an unnecessary second run of the CI after every PR merge onto master.
=> ci: don't run CI on merge to master (no longer necessary).

.github/workflows/main.yml
Reverts tylanphear/poet#11
It turns out that not running the CI on merge to `master` means we don't get a check mark on `master` anymore, which is annoying. Not worth it. The CI is quick so there's no real reason to avoid running it twice right now (and we should probably keep it quick).
=> Revert "ci: don't run CI on merge to master (no longer necessary)."

bootstrap.py, poet.toml
Using `latest` won't work right now because of breaking changes introduced in `0.2.0`.
(side note: yay, first win for `poet`!)
=> stanza-toml: pin version to `0.1.8`.

src/commands/init.stanza
Due to the removal of `TomlTable`'s printer in `stanza-toml` version `0.3.0`.
=> v0.1.1: fix `init` initial `poet.toml`

bootstrap.py, poet.toml, src/commands/build.stanza, src/utils.stanza
- Colorize output when emitting info, error and debug messages.
- Add a environment variable `POET_COLOR` that controls colorization behavior. It currently has two supported values:
- `always`: when set, `poet` always attempts to colorize output.
- `never`: when set, `poet` never attempts to colorize output.
When unset, colorization is always attempted. In the future, some level of terminal detection should be employed (e.g. to check if `poet`'s output is being redirected to a file)
=> v0.1.2: colorize output using `term-colors` when possible.

src/commands/build.stanza, src/commands/init.stanza, src/dependencies.stanza, src/dependency.stanza, src/logging.stanza, src/toml.stanza
Closes #36
User can now run: 
```
$> slm build tests
```
And slm will build the `tests` target in the project's `stanza.proj` file (assuming it exists).
=> Add Build Target and Fix Bugs

README.md, ci/download-stanza.sh, slm.toml, src/commands/build.stanza, src/commands/repl.stanza, src/commands/version.stanza, src/process-utils.stanza
This PR fixes some bugs and adds the ability to pull the version key from the `slm.toml` file and pass it to the library/binary being built as an environment variable. 
This requires stanza version 0.18.51 or greater. 
**Note** - If you want to try incrementing the version to see it update properly - you will likely need to run `stanza clean` to wipe the `pkg-cache`. Otherwise, the old version will be used and you will get an undesired result.
=> Add Version from EnvVar

src/commands/build.stanza, src/commands/repl.stanza, src/main.stanza, src/toml.stanza, src/utils.stanza
Closes JITX-7190
This allows the user to pass a differently named stanza executable via the `SLM_STANZA` environment variable. This allows the tool to build and work with `jstanza` for example.
=> Added the ability to change the `stanza` executable.

src/dependencies.stanza, src/dependency.stanza, src/main.stanza
Closes JITX-7205 and JITX-7192
This adds the ability to use environment variables in path dependency specifications.
It also fixes a bug where grand-children dependencies were not properly handled resulting in a crash.
=> Add Environment Variable Substitution in `PathDependency` & Bugfix

src/commands/init.stanza, src/commands/publish.stanza, src/dependencies.stanza, src/git-utils.stanza
Closes JITX-7204
This PR adds the ability to check for the `git` executable before running any of functionality in slm that depend on `git`. 
`init` - silently doesn't run `git init` - project should be fully functional otherwise.
`build/repl` - Throws an error if it needs to try and resolve any `git` based dependencies. Other dependencies (path dependencies) should resolve without issue. 
`publish` -  Fails outright without a git binary.
=> Graceful Degrade on `git`

.gitignore, slm.lock, slm.toml, src/commands.stanza, src/commands/add.stanza, src/commands/init.stanza, src/commands/remove.stanza, src/dependency.stanza, src/errors.stanza, src/git-utils.stanza, src/main.stanza, src/toml.stanza, src/utils.stanza, stanza.proj, tests/commands/add.stanza, tests/commands/remove.stanza, tests/data/test.toml, tests/git-utils.stanza, tests/test-tools.stanza, tests/toml.stanza, tests/utils.stanza
This PR adds: 
1.  The `add` and `remove` commands for dependencies: 
1.   You can run `slm add -git StanzaOrg/maybe-utils` and it will query Github, determine the latest version and then set that as the expected version in the `slm.toml` file.
2.  You can also override:
1.   The version with an explicit semantic version
2.  The name
2.  This introduces a unit-test framework that we can expand on and improve.
1.  I have tests for the `add` and `remove` functionality because I've written this code to be structured in a way that makes it more API friendly.
2.  This has the added benefit of being more easy to test. 
3.  We will need to work on refactoring other code to this model so that we can test and make an API from it. 
3.  I realized in doing this that the `add` function with the …
=> Add the `add` and `remove` commands for dependencies

README.md, src/commands/add.stanza, src/commands/build.stanza, src/commands/remove.stanza, src/commands/repl.stanza, src/dependencies.stanza, src/dependency.stanza, src/flags.stanza, src/logging.stanza, src/main.stanza, src/toml.stanza, tests/commands/add.stanza
Closes JITX-7201
1.  This refactors the `repl` and `build` commands to make it easier to pass arguments instead of using an EnvVar. I didn't realize there was a flag for `capture all remaining args` when I did the initial refactor. This setup is easier to integrate cleanly into JITX
2.  Changed the `slm.toml` parsing to not use env-var substitution during the `add` and `remove` commands. This was causing problems where the `{JITX_ROOT}` references were converted to literal paths on subsequent adds.
3.  Adds a new `-cfg` option for `add` and `remove` to avoid unnecessary `change directory`.
4.  Adds a version optional parameter for `PathDependency` so that we can spec a specific path dependency as needed.
=> Add Path Version Specifier and some bugfixes from integration

slm.toml, src/commands/add.stanza, src/dependency.stanza, src/main.stanza, src/toml.stanza, tests/data/error_git_path_mutex.toml, tests/data/error_no_git_or_path.toml, tests/toml.stanza
This refactors the git dependency specification from a custom string: 
`maybe-utils = "StanzaOrg/maybe-utils|0.1.5"`
To a standard TOML format like the `PathDependency`:
```
maybe-utils.git = "StanzaOrg/maybe-utils"
maybe-utils.version = "0.1.5"
```
I've left the legacy implementation in place to make upgrading easier. We can remove that as we get everything updated.
=> Refactor Git Dependencies to use standardize format

README.md, build_conan.ps1, build_conan.sh, conanfile.py, slm.toml
This refactors the `conanfile.py` to get a consistent hash id on different platforms.
Note also - that `git config core.autocrlf false` might also be necessary on windows so that the `conanfile.py` does not have `CRLF` line endings. 
I've added a script to help run the build on both linux/mac/windows.
I've confirmed that I get the same hash on mac and windows. I'll be checking linux shortly.
=> Fix Conan Build - Consistent Repo Hash IDs

slm.toml, src/commands/build.stanza, src/commands/repl.stanza
This adds a new env-var that should make it easier to use `conan`.
We should be able to do:
```
conan install --shared={SLM_BUILD_DYNAMIC_LIB} ...
```
=> Tweak EnvVars for Differentiating Shared vs Static

src/toml.stanza
Previously - I had added the `env-sub-enable` argument that made it so when parsing the slm toml file it didn't substitute the env vars for any of the values. This was necessary to support the `add` for path projects - specifically in JITX.
Somehow one of the functions that had this argument wasn't passing it on to the base class.
=> [Bugfix] Fixed the `add` command mangling the path dependencies

src/commands/init.stanza, src/git-utils.stanza, src/process-utils.stanza
Bhusan reported that when using `slm init` from with a sub-directory of an existing git repo, that the init command was constructing an unnecessary git repo.
This uses `git status` to check for a git repo as opposed to just checking for the `.git` directory.
=> Added a better check for the presence of a git repo in `init`

slm.toml, src/commands.stanza, src/commands/run.stanza, src/main.stanza
This pipes the `run` command to the `stanza` process via SLM.
This is a direct copy/pasta from `build` just to get this working. 
We might want to reorganize if we are going to support more stanza commands directly.
=> Add the `run` command

slm.toml, src/pkg-dep.stanza
- **Use full paths for pkg-dep extraction, and dont use tar -C feature due to windows symlink failure**
- **bump to 0.6.2**
=> Bump 0.6.2

conanfile.py, requirements.txt, slm.toml, slm_builder/Makefile, slm_builder/conan_lbstanza_generator/conanfile.py, slm_builder/conanfile.py, src/conan-utils.stanza, src/pkg-dep.stanza
- **slm_builder improvements for including compiled libs**
- **slm_builder improvements for windows path manipulation**
- **slm_builder/conanfile.py: apply platform-specific options from slm.toml dependencies**
- **slm_builder/Makefile: use conan profiles**
- **slm_builder/conan_lbstanza_generator: improve handling of dependency lib references**
- **Update conan builder files (2)**
- **slm_builder/conanfile.py: package libs from anywhere in the tree, not just the build dir**
- **slm_builder/conanfile.py: package libs from the lib dir, not the build dir**
- **conanfile.py: add dylib locations to DYLD_LIBRARY_PATH on mac for test execution**
- **slm_builder/conanfile.py: copy optional stanza-library.proj to export_sources dir**
- **slm_builder/conan_lbstanza_generator: improve detection of …
=> Standardize, rebuild, and update all dependencies. Update slm_builder files

src/main.stanza
Previous help text was using a static list, but wasn't updated with the new commands we have added. This adds the command list as a dynamically created string.
=> [Bugfix] Updated the command list in the help docs.

slm.toml, src/commands/add.stanza, src/dependencies.stanza, src/git-dep.stanza, src/git-utils.stanza, src/libgit-utils.stanza, src/main.stanza, src/utils.stanza, tests/git-utils.stanza
Adds libgit fallbacks for clone, fetch, checkout, lsremote, and rev-parse. Also changes the default SLM_PROTOCOL to HTTPS and adds an error if SSH is requested without Git installed. Does not add fallbacks for git push (for slm publish) and git init (for slm init) yet.
=> Jitx 8574/libgit2 integration

Makefile, conan_lbstanza_generator/conanfile.py, conanfile.py, slm_builder/conan_lbstanza_generator/conanfile.py, slm_builder/conanfile.py, src/commands/build.stanza, src/commands/repl.stanza, src/commands/run.stanza
In various `stanza.proj` files, I often encounter a pattern where I want to reference the top level `.slm` directory of a project. This ends up being a relative path reference with a `..` in it.
This poses a problem if you want to run the project locally to build, for example, the unit tests for a project.
This env-var makes it so the stanza.proj files don't have to use the relative path and can instead reference a direct location with `{SLM_DIR/deps/some-lib/...`
This is particularly present in [StanzaOrg/slm-z3](https://github.com/StanzaOrg/slm-z3). 
@jwatson0  - thoughts ?
=> Added the `SLM_DIR` environment variable.

Makefile, conan_lbstanza_generator/conanfile.py, conanfile.py, slm.toml, slm_builder/conan_lbstanza_generator/conanfile.py, slm_builder/conanfile.py, src/commands/build.stanza, src/commands/publish.stanza, src/commands/repl.stanza, src/commands/run.stanza, src/dependencies.stanza, src/stanza-utils.stanza, src/toml.stanza
* bump version of `slm-toml` dependency (this contains the actual parser fix)
* use `parse-file` API instead of `parse-string` -- this ensures that parser error messages will contain the actual file name (instead of the opaque `<input>:line:col` we see right now)
* rename `parse-slm-toml` to `parse-slm-toml-file` to clarify the fact that the string input is a filepath
* bump version
This depends on an `slm-toml` PR and release, will not merge until that gets in.
jitx ticket: PROD-213
=> .toml parsing bug

src/dependencies.stanza, src/dependency.stanza, src/git-dep.stanza, src/logging.stanza, src/path-dep.stanza, src/pkg-dep.stanza, src/task.stanza, src/toml.stanza
Adds support for nested path dependencies, mixed git and path dependencies (priority is given to the path dependency)
=> Prod 336/nested path dep

src/dependencies.stanza
Change the git dependency resolution to resync when the requested version is newer than the existing version (but not if its older and compatible).
=> Git resync for newer requested version

src/commands/init.stanza, src/file-utils.stanza, src/utils.stanza, stanza.proj, tests/file-utils.stanza, tests/libgit2.stanza, tests/toml.stanza
- remove buggy and confusing `first` function
- remove buggy `dir-name?` function
- use `base-name?` for package directory detection
- add test cases for `base-name?` function
- fix stale broken tests using `parse-slm-toml-file`
- fix cleanup in libgit test
- fix bug in `nth?`
=> Fix `package` path logic in generated `stanza.proj`

conanfile.py, requirements.txt, slm.toml
- **requirements.txt: pin to conan 2.7.1 temporarily**
- **conanfile.py: use vendor mode instead of unrelated_mode**
- **Release 0.6.18**
=> Change conan to Vendor mode to adapt to conan 2.8.0

ci/build-slm.sh, conanfile.py
- **conanfile.py: add option to codesign executable during packaging**
- **ci: use codesigning through makefile**
=> add option to codesign executable during conan packaging
